##
## Build
##

FROM golang:1.16-alpine as build

WORKDIR /app

COPY ./fib_grpc ./
RUN go mod download

RUN go build -o /fib_grpc fib_grpc

##
## Deploy
##

FROM alpine:3.10

WORKDIR /

COPY --from=build /fib_grpc /fib_grpc

EXPOSE 8070 8090

ENTRYPOINT ["./fib_grpc"]