version: "3.5"
services:
  server:
    container_name: fib_grpc
    image: fib_grpc:multistage
    network_mode: host
    expose:
      - 8090
      - 8070
    depends_on:
      - redis
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - INIT_SIZE=50
      - REDIS_PORT=6379
      - REDIS_ADDR=localhost
    restart: always

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    restart: always